export enum MASkillType {
  물 = '물',
  마 = '마',
  지 = '지',
  수 = '수',
  약 = '약',
  치 = '치',
}

export enum MAJobKind {
  강습 = '강습',
  지원 = '지원',
  수호 = '수호',
}

export enum MAGrade {
  'MR' = 'MR',
  'UR' = 'UR',
  'SR' = 'SR',
  'R' = 'R',
  'N' = 'N',
}

export interface MACard {
  name: string
  cost: number
  skillType: MASkillType
  jobKind: MAJobKind
  grade: MAGrade
}

export const MACardDict: {
  [key: any]: MACard
} = {
  1: {
    name: '감사형 우아사하',
    cost: 5,
    skillType: MASkillType.지,
    jobKind: MAJobKind.지원,
    grade: MAGrade.MR,
  },
  2: {
    name: '원정형 파르살리아',
    cost: 5,
    skillType: MASkillType.마,
    jobKind: MAJobKind.강습,
    grade: MAGrade.MR,
  },
  3: {
    name: '원정형 가희 아서',
    cost: 3,
    skillType: MASkillType.치,
    jobKind: MAJobKind.지원,
    grade: MAGrade.MR,
  },
  4: {
    name: '원정형 파르살리아',
    cost: 4,
    skillType: MASkillType.치,
    jobKind: MAJobKind.지원,
    grade: MAGrade.MR,
  },
  5: {
    name: '원정형 부호 아서',
    cost: 4,
    skillType: MASkillType.수,
    jobKind: MAJobKind.수호,
    grade: MAGrade.MR,
  },
  6: {
    name: '원정형 페리도트',
    cost: 3,
    skillType: MASkillType.수,
    jobKind: MAJobKind.수호,
    grade: MAGrade.MR,
  },
  7: {
    name: '원정형 파르살리아',
    cost: 3,
    skillType: MASkillType.물,
    jobKind: MAJobKind.수호,
    grade: MAGrade.MR,
  },
  8: {
    name: '원정형 도적 아서',
    cost: 5,
    skillType: MASkillType.물,
    jobKind: MAJobKind.강습,
    grade: MAGrade.MR,
  },
  9: {
    name: '원정형 용병 아서',
    cost: 4,
    skillType: MASkillType.물,
    jobKind: MAJobKind.강습,
    grade: MAGrade.MR,
  },

  10: {
    name: '통어형 폰 데어 탄',
    cost: 5,
    skillType: MASkillType.물,
    jobKind: MAJobKind.강습,
    grade: MAGrade.MR,
  },
  11: {
    name: '원정형 우아사하',
    cost: 4,
    skillType: MASkillType.마,
    jobKind: MAJobKind.강습,
    grade: MAGrade.MR,
  },
  12: {
    name: '원정형 쿠 훌린',
    cost: 4,
    skillType: MASkillType.지,
    jobKind: MAJobKind.강습,
    grade: MAGrade.MR,
  },
  13: {
    name: '복설형 단테',
    cost: 3,
    skillType: MASkillType.치,
    jobKind: MAJobKind.지원,
    grade: MAGrade.MR,
  },
  14: {
    name: '섬격형 오이페',
    cost: 5,
    skillType: MASkillType.물,
    jobKind: MAJobKind.강습,
    grade: MAGrade.MR,
  },
  15: {
    name: '작암형 폰 애쉬',
    cost: 3,
    skillType: MASkillType.약,
    jobKind: MAJobKind.강습,
    grade: MAGrade.MR,
  },
  16: {
    name: '말설형 가희 아서',
    cost: 4,
    skillType: MASkillType.마,
    jobKind: MAJobKind.지원,
    grade: MAGrade.MR,
  },
  17: {
    name: '원정형 우아사하',
    cost: 4,
    skillType: MASkillType.치,
    jobKind: MAJobKind.지원,
    grade: MAGrade.MR,
  },
  18: {
    name: '말설형 부호 아서',
    cost: 3,
    skillType: MASkillType.물,
    jobKind: MAJobKind.수호,
    grade: MAGrade.MR,
  },
  19: {
    name: '원정형 스카아하',
    cost: 2,
    skillType: MASkillType.지,
    jobKind: MAJobKind.수호,
    grade: MAGrade.MR,
  },

  20: {
    name: '파습형 폰 데어 탄',
    cost: 4,
    skillType: MASkillType.물,
    jobKind: MAJobKind.수호,
    grade: MAGrade.MR,
  },
  21: {
    name: '말설형 도적 아서',
    cost: 4,
    skillType: MASkillType.마,
    jobKind: MAJobKind.강습,
    grade: MAGrade.MR,
  },
  22: {
    name: '말설형 용병 아서',
    cost: 2,
    skillType: MASkillType.마,
    jobKind: MAJobKind.강습,
    grade: MAGrade.MR,
  },
  23: {
    name: '재절형 요르문간드',
    cost: 5,
    skillType: MASkillType.지,
    jobKind: MAJobKind.강습,
    grade: MAGrade.MR,
  },
  24: {
    name: '전주형 페델마',
    cost: 4,
    skillType: MASkillType.약,
    jobKind: MAJobKind.강습,
    grade: MAGrade.MR,
  },
  25: {
    name: '전주형 애니드',
    cost: 2,
    skillType: MASkillType.치,
    jobKind: MAJobKind.지원,
    grade: MAGrade.MR,
  },
  26: {
    name: '역경형 오이페',
    cost: 4,
    skillType: MASkillType.마,
    jobKind: MAJobKind.강습,
    grade: MAGrade.UR,
  },
  27: {
    name: '파빙형 가희 아서',
    cost: 3,
    skillType: MASkillType.치,
    jobKind: MAJobKind.지원,
    grade: MAGrade.UR,
  },
  28: {
    name: '이상형 도모보이',
    cost: 3,
    skillType: MASkillType.마,
    jobKind: MAJobKind.지원,
    grade: MAGrade.UR,
  },
  29: {
    name: '종말형 오프닐',
    cost: 4,
    skillType: MASkillType.약,
    jobKind: MAJobKind.지원,
    grade: MAGrade.MR,
  },

  30: {
    name: '초량형 중앙 시스템',
    cost: 5,
    skillType: MASkillType.마,
    jobKind: MAJobKind.지원,
    grade: MAGrade.MR,
  },
  31: {
    name: '파빙형 부호 아서',
    cost: 3,
    skillType: MASkillType.수,
    jobKind: MAJobKind.수호,
    grade: MAGrade.UR,
  },
  32: {
    name: '호령형 메이브',
    cost: 5,
    skillType: MASkillType.물,
    jobKind: MAJobKind.수호,
    grade: MAGrade.UR,
  },
  33: {
    name: '파빙형 도적 아서',
    cost: 3,
    skillType: MASkillType.마,
    jobKind: MAJobKind.강습,
    grade: MAGrade.UR,
  },
  34: {
    name: '파빙형 용병 아서',
    cost: 4,
    skillType: MASkillType.물,
    jobKind: MAJobKind.강습,
    grade: MAGrade.UR,
  },
  35: {
    name: '복설형 단테 수르트',
    cost: 3,
    skillType: MASkillType.물,
    jobKind: MAJobKind.강습,
    grade: MAGrade.UR,
  },
  36: {
    name: '복설형 페리도트',
    cost: 3,
    skillType: MASkillType.마,
    jobKind: MAJobKind.강습,
    grade: MAGrade.UR,
  },
  37: {
    name: '파습형 폰 애쉬',
    cost: 4,
    skillType: MASkillType.마,
    jobKind: MAJobKind.지원,
    grade: MAGrade.UR,
  },
  38: {
    name: '말설형 쿠 훌린',
    cost: 3,
    skillType: MASkillType.마,
    jobKind: MAJobKind.지원,
    grade: MAGrade.UR,
  },
  39: {
    name: '파빙형 스카아하',
    cost: 4,
    skillType: MASkillType.마,
    jobKind: MAJobKind.지원,
    grade: MAGrade.UR,
  },

  40: {
    name: '파습형 제국 정의의 기사',
    cost: 2,
    skillType: MASkillType.물,
    jobKind: MAJobKind.수호,
    grade: MAGrade.SR,
  },
  41: {
    name: '말설형 쿠 훌린',
    cost: 4,
    skillType: MASkillType.물,
    jobKind: MAJobKind.수호,
    grade: MAGrade.UR,
  },
  42: {
    name: '원정형 카라틴',
    cost: 2,
    skillType: MASkillType.수,
    jobKind: MAJobKind.수호,
    grade: MAGrade.UR,
  },
  43: {
    name: '파빙형 우아사하',
    cost: 3,
    skillType: MASkillType.수,
    jobKind: MAJobKind.수호,
    grade: MAGrade.UR,
  },
  44: {
    name: '파빙형 스카아하',
    cost: 3,
    skillType: MASkillType.물,
    jobKind: MAJobKind.강습,
    grade: MAGrade.UR,
  },
  45: {
    name: '원정형 카라틴',
    cost: 4,
    skillType: MASkillType.마,
    jobKind: MAJobKind.강습,
    grade: MAGrade.UR,
  },
  46: {
    name: '역경형 엘렉',
    cost: 3,
    skillType: MASkillType.지,
    jobKind: MAJobKind.강습,
    grade: MAGrade.UR,
  },
  47: {
    name: '원정형 카라틴',
    cost: 3,
    skillType: MASkillType.마,
    jobKind: MAJobKind.지원,
    grade: MAGrade.UR,
  },
  48: {
    name: '이상형 페델마',
    cost: 4,
    skillType: MASkillType.마,
    jobKind: MAJobKind.지원,
    grade: MAGrade.UR,
  },
  49: {
    name: '말설형 모르가즈',
    cost: 2,
    skillType: MASkillType.수,
    jobKind: MAJobKind.수호,
    grade: MAGrade.SR,
  },

  50: {
    name: '복설형 모건',
    cost: 2,
    skillType: MASkillType.마,
    jobKind: MAJobKind.강습,
    grade: MAGrade.SR,
  },
  51: {
    name: '통어형 폰 애쉬',
    cost: 3,
    skillType: MASkillType.마,
    jobKind: MAJobKind.강습,
    grade: MAGrade.SR,
  },
  52: {
    name: '기상형 도모보이',
    cost: 2,
    skillType: MASkillType.치,
    jobKind: MAJobKind.지원,
    grade: MAGrade.SR,
  },
  53: {
    name: '정념형 애니드',
    cost: 3,
    skillType: MASkillType.물,
    jobKind: MAJobKind.수호,
    grade: MAGrade.SR,
  },
  54: {
    name: '방주형 요르문간드',
    cost: 4,
    skillType: MASkillType.물,
    jobKind: MAJobKind.수호,
    grade: MAGrade.SR,
  },
  55: {
    name: '복설형 쿠 훌린',
    cost: 2,
    skillType: MASkillType.물,
    jobKind: MAJobKind.수호,
    grade: MAGrade.SR,
  },
  56: {
    name: '방어형 중앙 시스템',
    cost: 3,
    skillType: MASkillType.수,
    jobKind: MAJobKind.수호,
    grade: MAGrade.SR,
  },
  57: {
    name: '성장형 메이브',
    cost: 2,
    skillType: MASkillType.물,
    jobKind: MAJobKind.강습,
    grade: MAGrade.SR,
  },
  58: {
    name: '휴게형 파르살리아',
    cost: 2,
    skillType: MASkillType.지,
    jobKind: MAJobKind.강습,
    grade: MAGrade.SR,
  },
  59: {
    name: '황수형 오프닐',
    cost: 3,
    skillType: MASkillType.물,
    jobKind: MAJobKind.강습,
    grade: MAGrade.SR,
  },

  60: {
    name: '유탕형 공포의 혼령',
    cost: 4,
    skillType: MASkillType.물,
    jobKind: MAJobKind.강습,
    grade: MAGrade.SR,
  },
  61: {
    name: '정념형 엘렉',
    cost: 2,
    skillType: MASkillType.지,
    jobKind: MAJobKind.지원,
    grade: MAGrade.SR,
  },
  62: {
    name: '복설형 펜리르의 후예',
    cost: 3,
    skillType: MASkillType.물,
    jobKind: MAJobKind.강습,
    grade: MAGrade.SR,
  },
  63: {
    name: '이상형 니무에',
    cost: 2,
    skillType: MASkillType.치,
    jobKind: MAJobKind.지원,
    grade: MAGrade.SR,
  },
  64: {
    name: '영호형 우아사하',
    cost: 3,
    skillType: MASkillType.수,
    jobKind: MAJobKind.지원,
    grade: MAGrade.SR,
  },
  65: {
    name: '복설형 엘레인',
    cost: 2,
    skillType: MASkillType.지,
    jobKind: MAJobKind.지원,
    grade: MAGrade.SR,
  },
  66: {
    name: '말설형 단테 수르트',
    cost: 3,
    skillType: MASkillType.마,
    jobKind: MAJobKind.지원,
    grade: MAGrade.SR,
  },
  67: {
    name: '기상형 페델마',
    cost: 3,
    skillType: MASkillType.지,
    jobKind: MAJobKind.지원,
    grade: MAGrade.SR,
  },
  68: {
    name: '추적형 제국 이단 심문관',
    cost: 4,
    skillType: MASkillType.마,
    jobKind: MAJobKind.지원,
    grade: MAGrade.SR,
  },
  69: {
    name: '정념형 엘렉',
    cost: 2,
    skillType: MASkillType.지,
    jobKind: MAJobKind.지원,
    grade: MAGrade.SR,
  },

  70: {
    name: '복설형 수르트',
    cost: 3,
    skillType: MASkillType.물,
    jobKind: MAJobKind.수호,
    grade: MAGrade.SR,
  },
  71: {
    name: '원정형 엘렉',
    cost: 2,
    skillType: MASkillType.물,
    jobKind: MAJobKind.강습,
    grade: MAGrade.SR,
  },
  72: {
    name: '원정형 니무에',
    cost: 2,
    skillType: MASkillType.약,
    jobKind: MAJobKind.강습,
    grade: MAGrade.SR,
  },
  73: {
    name: '원정형 오이페',
    cost: 3,
    skillType: MASkillType.물,
    jobKind: MAJobKind.수호,
    grade: MAGrade.SR,
  },
  74: {
    name: '실심형 경비원',
    cost: 1,
    skillType: MASkillType.수,
    jobKind: MAJobKind.수호,
    grade: MAGrade.R,
  },
  75: {
    name: '단조형 거인',
    cost: 2,
    skillType: MASkillType.물,
    jobKind: MAJobKind.강습,
    grade: MAGrade.R,
  },
  76: {
    name: '돌변형 북쪽 거대 늑대',
    cost: 2,
    skillType: MASkillType.약,
    jobKind: MAJobKind.강습,
    grade: MAGrade.R,
  },
  77: {
    name: '서수형 메이브',
    cost: 4,
    skillType: MASkillType.수,
    jobKind: MAJobKind.수호,
    grade: MAGrade.SR,
  },
  78: {
    name: '영호형 스카아하',
    cost: 4,
    skillType: MASkillType.물,
    jobKind: MAJobKind.수호,
    grade: MAGrade.SR,
  },
  79: {
    name: '원정형 애니드',
    cost: 2,
    skillType: MASkillType.지,
    jobKind: MAJobKind.강습,
    grade: MAGrade.SR,
  },

  80: {
    name: '원정형 모건',
    cost: 2,
    skillType: MASkillType.마,
    jobKind: MAJobKind.강습,
    grade: MAGrade.SR,
  },
  81: {
    name: '탁식형 엘레인',
    cost: 3,
    skillType: MASkillType.지,
    jobKind: MAJobKind.강습,
    grade: MAGrade.SR,
  },
  82: {
    name: '각력형 카라틴',
    cost: 3,
    skillType: MASkillType.물,
    jobKind: MAJobKind.강습,
    grade: MAGrade.SR,
  },
  83: {
    name: '복설형 모르가즈',
    cost: 3,
    skillType: MASkillType.치,
    jobKind: MAJobKind.지원,
    grade: MAGrade.SR,
  },
  84: {
    name: '중주형 거인',
    cost: 2,
    skillType: MASkillType.물,
    jobKind: MAJobKind.수호,
    grade: MAGrade.R,
  },
  85: {
    name: '실심형 연구원',
    cost: 2,
    skillType: MASkillType.마,
    jobKind: MAJobKind.지원,
    grade: MAGrade.R,
  },
  86: {
    name: '감관형 기생체',
    cost: 1,
    skillType: MASkillType.지,
    jobKind: MAJobKind.지원,
    grade: MAGrade.R,
  },
  87: {
    name: '파습형 제국 돌격병',
    cost: 1,
    skillType: MASkillType.물,
    jobKind: MAJobKind.수호,
    grade: MAGrade.N,
  },
  88: {
    name: '파습형 제국 형벌병',
    cost: 2,
    skillType: MASkillType.물,
    jobKind: MAJobKind.수호,
    grade: MAGrade.N,
  },
  89: {
    name: '선봉형 브리틴 병사',
    cost: 2,
    skillType: MASkillType.마,
    jobKind: MAJobKind.강습,
    grade: MAGrade.N,
  },

  90: {
    name: '황수형 북쪽 거대 늑대',
    cost: 1,
    skillType: MASkillType.약,
    jobKind: MAJobKind.강습,
    grade: MAGrade.N,
  },
  91: {
    name: '지원형 브리튼 병사',
    cost: 1,
    skillType: MASkillType.치,
    jobKind: MAJobKind.지원,
    grade: MAGrade.N,
  },
  92: {
    name: '파습형 제국 저격병',
    cost: 1,
    skillType: MASkillType.지,
    jobKind: MAJobKind.지원,
    grade: MAGrade.N,
  },
}
